Repository sleppy-navigators/study-up-backend, pull requests merged in 2025-02, with the labels that each got.

#12 Feat : basic google social authentication
  build.gradle
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthProvider.java
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthService.java
  src/main/java/sleppynavigators/studyupbackend/application/user/UserService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManager.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/UserSession.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/token/AccessToken.java
  src/main/java/sleppynavigators/studyupbackend/domain/user/vo/SampleVO.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/config/HttpClientConfig.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/GoogleOidcClient.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/GoogleProperties.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/OidcClient.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/session/UserSessionRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/AuthController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/RefreshRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/SignInRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/TokenResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/AccessTokenAuthenticationFilter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/UserAuthentication.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/UserPrincipal.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/config/SwaggerConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/UserController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/dto/SampleResponse.java
  src/main/resources/application.yaml
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManagerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
Labels: enhancement, size/XXL

#13 Refactor : new Exception Handling System
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthService.java
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManager.java
  src/main/java/sleppynavigators/studyupbackend/exception/BaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorResponse.java
  src/main/java/sleppynavigators/studyupbackend/exception/GlobalExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/exception/UnknownException.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/BusinessBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/SessionExpiredException.java
  src/main/java/sleppynavigators/studyupbackend/exception/client/ClientBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/client/UnsuccessfulResponseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/database/DatabaseBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/database/EntityNotFoundException.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/ForbiddenException.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/InvalidApiException.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/InvalidCredentialException.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/NetworkBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/UnAuthorizedException.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/GoogleOidcClient.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/AuthController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/config/SecurityConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/exception/InvalidCredentialException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/exception/SessionExpiredException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/AccessTokenAuthenticationFilter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/controller/ChatDocumentationController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/exception/ChatMessageException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/handler/WebSocketExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/APIResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/APIResult.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/ClientException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/GlobalExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/SuccessResponse.java
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManagerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandlerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/support/WebSocketTestSupport.java
Labels: enhancement, size/XL

#16 Feat : basic group api
  src/main/java/sleppynavigators/studyupbackend/StudyUpBackendApplication.java
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthService.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/UserCredential.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/UserSession.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/Group.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/GroupMember.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/vo/GroupDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/user/User.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/GlobalExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/InvalidCredentialException.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/GoogleOidcClient.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupMemberRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/AuthController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/TokenResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/request/RefreshRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/request/SignInRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/response/TokenResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/request/GroupCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupInvitationResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/SimpleGroupResponse.java
  src/main/resources/application.yaml
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/common/DatabaseCleaner.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
Labels: enhancement, size/XL

#17 Spring STOMP에 시큐리티 기반 인증/인가 반영
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatService.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorResponse.java
  src/main/java/sleppynavigators/studyupbackend/exception/RestApiExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/exception/WebSocketExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/ChatMessageException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/config/SecurityConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/AccessTokenAuthenticationFilter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/UserAuthentication.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/config/WebSocketConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/ChatMessageRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/exception/ChatMessageException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/handler/WebSocketExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/interceptor/StompAuthenticationInterceptor.java
  src/main/java/sleppynavigators/studyupbackend/presentation/util/AuthenticationConverter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/util/BearerTokenExtractor.java
  src/main/resources/templates/chat.html
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandlerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/support/WebSocketTestSupport.java
Labels: size/XL

#18 Fix : fix api tests
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/UserCredential.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/UserSession.java
  src/main/java/sleppynavigators/studyupbackend/domain/user/User.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/GoogleOidcClient.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupRepository.java
  src/test/java/sleppynavigators/studyupbackend/StudyUpBackendApplicationTests.java
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManagerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandlerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/common/DatabaseCleaner.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
Labels: enhancement, size/L

#19 Style : reformat all
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthService.java
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManager.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorResponse.java
  src/main/java/sleppynavigators/studyupbackend/exception/WebSocketExceptionHandler.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/BusinessBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/client/ClientBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/database/DatabaseBaseException.java
  src/main/java/sleppynavigators/studyupbackend/exception/network/NetworkBaseException.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/AuthController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/config/SecurityConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/AccessTokenAuthenticationFilter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/UserAuthentication.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/config/WebSocketConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/ChatMessageRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/ChatMessageResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/util/AuthenticationConverter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/util/BearerTokenExtractor.java
  src/main/resources/templates/chat.html
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManagerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandlerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/support/WebSocketTestSupport.java
Labels: enhancement, size/L

#20 Feat : group invitation
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/Group.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/GroupMember.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/invitation/GroupInvitation.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/InvalidPayloadException.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/invitation/GroupInvitationRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/filter/AccessTokenAuthenticationFilter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/interceptor/StompAuthenticationInterceptor.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/config/SwaggerConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/util/AuthenticationConverter.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/util/BearerTokenExtractor.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/request/GroupInvitationAcceptRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupInvitationResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupResponse.java
  src/test/java/sleppynavigators/studyupbackend/presentation/common/DatabaseCleaner.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/resources/application-test.yaml
Labels: enhancement, size/L
