Repository sleppy-navigators/study-up-backend, pull requests merged in 2025-05, with the labels that each got.

#54 Chore : rename service
  docker-compose.yaml
Labels: enhancement, size/XS

#55 Chore : rename compose service for loki compatibility2
  .github/workflows/cd.yaml
  docker-compose.yaml
Labels: enhancement, size/S

#58 Docs : expose query strings more readable
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/ChallengeSearch.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/TaskSearch.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/request/ChatMessageSearch.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/request/GroupSearch.java
Labels: documentation, size/XS

#56 Feat : event when task certified
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/ChallengeDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/ChallengeCompleteSystemMessageGenerator.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/TaskCertifySystemMessageGenerator.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCompleteEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/EventType.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/TaskCertifyEvent.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeQueryOptions.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeQueryRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeQueryRepositoryImpl.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/scheduler/ChallengeScheduler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/ChallengeCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/ChallengeResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupChallengeListResponse.java
  src/test/java/sleppynavigators/studyupbackend/application/challenge/ChallengeServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatMessageServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/group/GroupServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/common/support/ChallengeSupport.java
  src/test/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/ChallengeCompleteSystemMessageGeneratorTest.java
  src/test/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/TaskCertifySystemMessageGeneratorTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
Labels: enhancement, size/L

#60 Feat : point base
  build.gradle
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/event/SystemEventListener.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/ChallengeDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCompleteEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/point/vo/Point.java
  src/main/java/sleppynavigators/studyupbackend/domain/user/User.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/ChallengeInProgressException.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/ChatMessageException.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/InSufficientPointsException.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeQueryOptions.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/scheduler/ChallengeScheduler.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/user/UserRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/ChallengeCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/ChallengeResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskChallengeDTO.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupChallengeListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/dto/response/UserResponse.java
  src/main/resources/db/migration/V0.0.0__ddl.sql
  src/main/resources/db/migration/V0.0.1__points.sql
  src/test/java/sleppynavigators/studyupbackend/application/challenge/ChallengeServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/common/DatabaseCleaner.java
  src/test/java/sleppynavigators/studyupbackend/common/support/ChallengeSupport.java
  src/test/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/ChallengeCompleteSystemMessageGeneratorTest.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/challenge/scheduler/ChallengeSchedulerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
  src/test/resources/application-test.yaml
Labels: enhancement, size/XL

#62 spring event 기반 FCM 알림 기능 구현
  .cursor/rules/coding-convension.mdc
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatMessageService.java
  src/main/java/sleppynavigators/studyupbackend/application/event/ChallengeEventListener.java
  src/main/java/sleppynavigators/studyupbackend/application/event/ChallengeEventPublisher.java
  src/main/java/sleppynavigators/studyupbackend/application/event/NotificationEventListener.java
  src/main/java/sleppynavigators/studyupbackend/application/event/NotificationEventPublisher.java
  src/main/java/sleppynavigators/studyupbackend/application/event/SystemMessageEventListener.java
  src/main/java/sleppynavigators/studyupbackend/application/event/SystemMessageEventPublisher.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/application/notification/FcmNotificationService.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/SystemMessageGenerator.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/systemmessage/SystemMessageGeneratorFactory.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCancelEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCompleteEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCreateEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/Event.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/EventType.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/GroupCreateEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/GroupNotificationEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/NotificationEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/PersonalNotificationEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/SystemMessageEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/TaskCertifyEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/UserJoinEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/UserLeaveEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/notification/ChallengeCompleteNotificationMessageGenerator.java
  src/main/java/sleppynavigators/studyupbackend/domain/notification/NotificationMessage.java
  src/main/java/sleppynavigators/studyupbackend/domain/notification/NotificationMessageGenerator.java
  src/main/java/sleppynavigators/studyupbackend/domain/notification/NotificationMessageGeneratorFactory.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/scheduler/ChallengeScheduler.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/notification/FcmClient.java
  src/test/java/sleppynavigators/studyupbackend/application/challenge/ChallengeServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatMessageServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/group/GroupServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/notification/FcmNotificationServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/common/support/GroupSupport.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/challenge/scheduler/ChallengeSchedulerTest.java
Labels: size/XL

#64 Feat : hunting base
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Task.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/hunting/Hunting.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/hunting/vo/Deposit.java
  src/main/java/sleppynavigators/studyupbackend/domain/user/User.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/hunting/HuntingRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/ChallengeResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/HuntingResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskChallengeDTO.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupChallengeListResponse.java
  src/main/resources/db/migration/V0.0.2__huntings.sql
  src/test/java/sleppynavigators/studyupbackend/application/challenge/ChallengeServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/common/support/ChallengeSupport.java
  src/test/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
Labels: enhancement, size/L

#66 Feat : ranking base
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupMemberSortType.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/GroupMember.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/scheduler/ChallengeScheduler.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupMemberRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/argument/GroupMemberSearchArgumentResolver.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/config/WebConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/request/GroupMemberSearch.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupMemberListResponse.java
  src/test/java/sleppynavigators/studyupbackend/common/support/UserSupport.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
Labels: enhancement, size/L
