Repository sleppy-navigators/study-up-backend, pull requests merged in 2025-03, with the labels that each got.

#24 Chore : basic ci
  .github/workflows/ci.yaml
  build.gradle
  src/main/java/sleppynavigators/studyupbackend/presentation/common/config/CorsConfig.java
  src/main/java/sleppynavigators/studyupbackend/presentation/common/config/SwaggerConfig.java
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
Labels: enhancement, size/M

#23 그룹방의 채팅 조회하는 API 구현
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatMessageService.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/response/ChatMessageDto.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/response/ChatMessageListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandler.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatMessageServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/common/DatabaseCleaner.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
Labels: size/L

#27 Feat/basic challenge business
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/application/user/UserService.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/TaskRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/UserController.java
  src/test/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
Labels: enhancement, size/XL

#28 Refactor : basic challenge domains
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/application/user/UserService.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Task.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/ChallengeDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/Deadline.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/TaskCertification.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/TaskDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/Title.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/Group.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/vo/GroupDetail.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/ForbiddenContentException.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/OveredDeadlineException.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/TaskRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/common/attribute/converter/UrlConverter.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/ChallengeCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/TaskCertificationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/ChallengeResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskCertificationDTO.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/request/GroupCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupChallengeListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupTaskListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/UserController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/dto/response/UserTaskListResponse.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/common/attribute/converter/UrlConverterTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
Labels: enhancement, size/XXL

#26 Feat : basic challenge api
  .github/workflows/ci.yaml
  .gitignore
  build.gradle
  src/main/java/sleppynavigators/studyupbackend/application/authentication/AuthService.java
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/application/user/UserService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/token/AccessToken.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Task.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/ChallengeDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/Deadline.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/TaskCertification.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/TaskDetail.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/vo/Title.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/Group.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/vo/GroupDetail.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/ForbiddenContentException.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/OveredDeadlineException.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/authentication/oidc/GoogleOidcClient.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/TaskRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/common/attribute/converter/UrlConverter.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/group/GroupRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/ChallengeCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/request/TaskCertificationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/ChallengeResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskCertificationDTO.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/GroupController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/request/GroupCreationRequest.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupChallengeListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupTaskListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/UserController.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/dto/response/UserTaskListResponse.java
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/common/attribute/converter/UrlConverterTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
Labels: enhancement, size/XXL

#29 Feat : block challenger leave group
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/token/AccessToken.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Task.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/Group.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/invitation/GroupInvitation.java
  src/main/java/sleppynavigators/studyupbackend/exception/ErrorCode.java
  src/main/java/sleppynavigators/studyupbackend/exception/business/ActionRequiredBeforeException.java
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
Labels: enhancement, size/L

#30 Feat : basic base entities
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/UserCredential.java
  src/main/java/sleppynavigators/studyupbackend/domain/authentication/session/UserSession.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Task.java
  src/main/java/sleppynavigators/studyupbackend/domain/common/TimeAuditBaseEntity.java
  src/main/java/sleppynavigators/studyupbackend/domain/common/UserAndTimeAuditBaseEntity.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/Group.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/GroupMember.java
  src/main/java/sleppynavigators/studyupbackend/domain/group/invitation/GroupInvitation.java
  src/main/java/sleppynavigators/studyupbackend/domain/user/User.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/common/config/JpaConfig.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/common/config/UserIdAuditorAware.java
Labels: enhancement, size/L

#34 Bot 정의 및 시스템 메시지 정의
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatMessageService.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/bot/Bot.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/ChatMessage.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/SenderType.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/SystemMessageTemplate.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/Event.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/bot/BotRepository.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/ChatMessageResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/response/ChatMessageDto.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/handler/ChatMessageHandler.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatMessageServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/chat/ChatMessageRepositoryTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
Labels: size/L

#39 시스템 메시지 pub/sub 구현
  src/main/java/sleppynavigators/studyupbackend/StudyUpBackendApplication.java
  src/main/java/sleppynavigators/studyupbackend/application/challenge/ChallengeService.java
  src/main/java/sleppynavigators/studyupbackend/application/chat/ChatMessageService.java
  src/main/java/sleppynavigators/studyupbackend/application/event/SystemEventListener.java
  src/main/java/sleppynavigators/studyupbackend/application/event/SystemEventPublisher.java
  src/main/java/sleppynavigators/studyupbackend/application/group/GroupService.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Challenge.java
  src/main/java/sleppynavigators/studyupbackend/domain/challenge/Task.java
  src/main/java/sleppynavigators/studyupbackend/domain/chat/SystemMessageTemplate.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCompleteEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/ChallengeCreateEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/SystemEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/SystemEventType.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/UserJoinEvent.java
  src/main/java/sleppynavigators/studyupbackend/domain/event/UserLeaveEvent.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/challenge/ChallengeRepository.java
  src/main/java/sleppynavigators/studyupbackend/infrastructure/scheduler/ChallengeScheduler.java
  src/test/java/sleppynavigators/studyupbackend/application/challenge/ChallengeServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatMessageServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/group/GroupServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/domain/event/SystemEventTest.java
Labels: size/XL

#36 Fix : restassured field assertaion
  .github/workflows/ci.yaml
  src/main/java/sleppynavigators/studyupbackend/domain/group/invitation/GroupInvitation.java
  src/main/java/sleppynavigators/studyupbackend/presentation/authentication/dto/response/TokenResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/ChallengeResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskCertificationDTO.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/challenge/dto/response/TaskResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/response/ChatMessageDto.java
  src/main/java/sleppynavigators/studyupbackend/presentation/chat/dto/response/ChatMessageListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupChallengeListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupInvitationResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/group/dto/response/GroupTaskListResponse.java
  src/main/java/sleppynavigators/studyupbackend/presentation/user/dto/response/UserTaskListResponse.java
  src/test/java/sleppynavigators/studyupbackend/application/authentication/AuthServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/challenge/ChallengeServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/chat/ChatMessageServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/application/group/GroupServiceTest.java
  src/test/java/sleppynavigators/studyupbackend/common/ApplicationBaseTest.java
  src/test/java/sleppynavigators/studyupbackend/common/DatabaseCleaner.java
  src/test/java/sleppynavigators/studyupbackend/common/IntegrationBaseTest.java
  src/test/java/sleppynavigators/studyupbackend/common/RestAssuredBaseTest.java
  src/test/java/sleppynavigators/studyupbackend/common/support/AuthSupport.java
  src/test/java/sleppynavigators/studyupbackend/common/support/BotSupport.java
  src/test/java/sleppynavigators/studyupbackend/common/support/ChallengeSupport.java
  src/test/java/sleppynavigators/studyupbackend/common/support/GroupSupport.java
  src/test/java/sleppynavigators/studyupbackend/common/support/UserSupport.java
  src/test/java/sleppynavigators/studyupbackend/common/support/WebSocketTestSupport.java
  src/test/java/sleppynavigators/studyupbackend/domain/authentication/session/SessionManagerTest.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/chat/ChatMessageRepositoryTest.java
  src/test/java/sleppynavigators/studyupbackend/infrastructure/common/attribute/converter/UrlConverterTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/authentication/AuthControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/challenge/ChallengeControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/chat/ChatMessageHandlerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/group/GroupControllerTest.java
  src/test/java/sleppynavigators/studyupbackend/presentation/user/UserControllerTest.java
Labels: bug, size/XXL
